use_frameworks!

platform :ios, '10.0'

target 'RKCustomMediaPicker_Example' do
  pod 'RKCustomMediaPicker', :path => '../'

  target 'RKCustomMediaPicker_Tests' do
    inherit! :search_paths

    
  end
end
